// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP6QCMl9u72xssYcWXlt5PCZV6WzM6chc',
    appId: '1:853468185307:web:78888fbe6acbfe24bd82fe',
    messagingSenderId: '853468185307',
    projectId: 'organization-self-stack',
    authDomain: 'organization-self-stack.firebaseapp.com',
    storageBucket: 'organization-self-stack.appspot.com',
    measurementId: 'G-6LRQMS18TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXvw9Yj1v3sUdoe1EH9l5pNyQJmb_ahQo',
    appId: '1:853468185307:android:65366c02e52a4c64bd82fe',
    messagingSenderId: '853468185307',
    projectId: 'organization-self-stack',
    storageBucket: 'organization-self-stack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdYcTn4q_ZvHRuFUWU1k-9JnnIluALFnI',
    appId: '1:853468185307:ios:29a64e3da2a50f09bd82fe',
    messagingSenderId: '853468185307',
    projectId: 'organization-self-stack',
    storageBucket: 'organization-self-stack.appspot.com',
    iosClientId: '853468185307-kbrsgko9p7qsdmvoqh5428jkpdp1aecm.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfStack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdYcTn4q_ZvHRuFUWU1k-9JnnIluALFnI',
    appId: '1:853468185307:ios:61cd61dcce1c1721bd82fe',
    messagingSenderId: '853468185307',
    projectId: 'organization-self-stack',
    storageBucket: 'organization-self-stack.appspot.com',
    iosClientId: '853468185307-j5f3iuq2i5bbnt4ckgollu5qgh0nds50.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfStack.RunnerTests',
  );
}
