// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2yeZowOvOluchF6dmMRroe1aETl_9bNw',
    appId: '1:569932012172:web:6bf9c82c84078e939639a9',
    messagingSenderId: '569932012172',
    projectId: 'self-stack-project',
    authDomain: 'self-stack-project.firebaseapp.com',
    storageBucket: 'self-stack-project.appspot.com',
    measurementId: 'G-H778E1P3HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYXY8GjaX54ZemAUMuXSQRw2DddSk-X9k',
    appId: '1:569932012172:android:04f61e6cbaf593e39639a9',
    messagingSenderId: '569932012172',
    projectId: 'self-stack-project',
    storageBucket: 'self-stack-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWHZIAN4_05cW9JBl3kcNkBx7djOROuik',
    appId: '1:569932012172:ios:97bb88bf96a904119639a9',
    messagingSenderId: '569932012172',
    projectId: 'self-stack-project',
    storageBucket: 'self-stack-project.appspot.com',
    iosBundleId: 'com.example.selfStack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWHZIAN4_05cW9JBl3kcNkBx7djOROuik',
    appId: '1:569932012172:ios:8b9ca3a5f69284389639a9',
    messagingSenderId: '569932012172',
    projectId: 'self-stack-project',
    storageBucket: 'self-stack-project.appspot.com',
    iosBundleId: 'com.example.selfStack.RunnerTests',
  );
}
